version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "snowflake-ml-stack-poc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tfzk0ms4cp9b"
s3_prefix = "snowflake-ml-stack-poc"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["InferenceFunction=183626424367.dkr.ecr.us-east-1.amazonaws.com/snowflake-ml-inference"]
