AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for snowflake-ml-stack

Globals:
  Function:
    Timeout: 60

Resources:
  InferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      #ImageConfig:
      #  Command: [ "app.lambda_handler" ]
      Events:
        PostRequest:
          Type: HttpApi
          Properties:
            Path: /inference
            Method: POST
            PayloadFormatVersion: '2.0' # see https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html for 2.0 payload
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./inference_service
      DockerTag: v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InferenceFunctionHttpApi:
    Description: "API Gateway endpoint URL for Prod stage for the inference function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/inference/"
  InferenceFunction:
    Description: "Inference Function ARN"
    Value: !GetAtt InferenceFunction.Arn
